import { Adapter, GattLocal, Peripheral } from '../../models';
import { HciPeripheral } from './Peripheral';
export declare class HciAdapter extends Adapter {
    private initialized;
    private scanning;
    private advertising;
    private requestScanStop;
    private hci;
    private gap;
    private gatt;
    private deviceName;
    private peripherals;
    private uuidToHandle;
    private handleToUUID;
    private connectionRequest;
    private connectionRequestQueue;
    getScannedPeripherals(): Promise<Peripheral[]>;
    isScanning(): Promise<boolean>;
    private init;
    dispose(): void;
    startScanning(): Promise<void>;
    private onScanStart;
    stopScanning(): Promise<void>;
    private onScanStop;
    private onDiscover;
    connect(peripheral: HciPeripheral): Promise<void>;
    private onLeConnComplete;
    private processConnectionRequests;
    disconnect(peripheral: HciPeripheral): Promise<number>;
    startAdvertising(deviceName: string, serviceUUIDs?: string[]): Promise<void>;
    private onAdvertisingStart;
    stopAdvertising(): Promise<void>;
    private onAdvertisingStop;
    setupGatt(maxMtu?: number): Promise<GattLocal>;
}
