/// <reference types="node" />
import { EventEmitter } from 'events';
import { AddressType } from '../../../types';
interface HciDevice {
    devId: number;
    devUp: boolean;
    idVendor: null;
    idProduct: null;
    busNumber: null;
    name: string;
    address: string;
}
declare type StateChangeListener = (newState: string) => void;
declare type AclDataPacketListener = (handle: number, cid: number, data: Buffer) => void;
declare type LeScanEnableListener = (enabled: boolean, filterDuplicates: boolean) => void;
declare type LeConnCompleteListener = (status: number, handle: number, role: number, addressType: AddressType, address: string, interval: number, latency: number, supervisionTimeout: number, masterClockAccuracy: number) => void;
declare type DisconnectCompleteListener = (status: number, handle: number, reason: number) => void;
declare type LeAdvertisingReportListener = (type: number, address: string, addressType: AddressType, eir: Buffer, rssi: number) => void;
declare type LeAdvertiseEnableListener = (enabled: boolean) => void;
export declare interface Hci {
    on(event: 'stateChange', listener: StateChangeListener): this;
    on(event: 'aclDataPkt', listener: AclDataPacketListener): this;
    on(event: 'leScanEnable', listener: LeScanEnableListener): this;
    on(event: 'leConnComplete', listener: LeConnCompleteListener): this;
    on(event: 'disconnectComplete', listener: DisconnectCompleteListener): this;
    on(event: 'leAdvertiseEnable', listener: LeAdvertiseEnableListener): this;
    on(event: 'leAdvertisingReport', listener: LeAdvertisingReportListener): this;
}
export declare class Hci extends EventEmitter {
    state: string;
    deviceId: number;
    addressType: AddressType;
    address: string;
    hciVersion: number;
    hciRevision: number;
    private socket;
    private socketTimer;
    private isSocketUp;
    private handles;
    private mutex;
    private currentCmd;
    private cmdTimeout;
    private aclDataPacketLength;
    private totalNumAclDataPackets;
    private aclLeDataPacketLength;
    private totalNumAclLeDataPackets;
    private aclPacketQueue;
    constructor(deviceId?: number, cmdTimeout?: number);
    static getDeviceList(): HciDevice[];
    init(): Promise<void>;
    private checkSocketState;
    dispose(): void;
    private sendCommand;
    private setSocketFilter;
    private setEventMask;
    private reset;
    private readLocalVersion;
    private readBdAddr;
    private setLeEventMask;
    private readLeHostSupported;
    private writeLeHostSupported;
    setScanParameters(): Promise<void>;
    setScanEnabled(enabled: boolean, filterDuplicates: boolean): Promise<void>;
    createLeConn(address: string, addressType: AddressType): Promise<number>;
    cancelLeConn(): Promise<void>;
    connUpdateLe(handle: number, minInterval: number, maxInterval: number, latency: number, supervisionTimeout: number): void;
    startLeEncryption(handle: number, random: any, diversifier: Buffer, key: Buffer): void;
    disconnect(handle: number, reason?: number): Promise<void>;
    readRssi(handle: number): Promise<number>;
    writeAclDataPkt(handleId: number, cid: number, data: Buffer): void;
    private processAclPacketQueue;
    readBufferSize(): Promise<void>;
    readLeBufferSize(): Promise<void>;
    setScanResponseData(data: Buffer): Promise<void>;
    setAdvertisingData(data: Buffer): Promise<void>;
    setAdvertisingEnabled(enabled: boolean): Promise<void>;
    private onSocketData;
    private onSocketError;
    private processLeConnComplete;
    private processLeAdvertisingReport;
}
export {};
