export declare const HCI_COMMAND_PKT = 1;
export declare const HCI_ACLDATA_PKT = 2;
export declare const HCI_EVENT_PKT = 4;
export declare const ACL_START_NO_FLUSH = 0;
export declare const ACL_CONT = 1;
export declare const ACL_START = 2;
export declare const EVT_DISCONN_COMPLETE = 5;
export declare const EVT_ENCRYPT_CHANGE = 8;
export declare const EVT_QOS_COMPLETE = 13;
export declare const EVT_CMD_COMPLETE = 14;
export declare const EVT_CMD_STATUS = 15;
export declare const EVT_HARDWARE_ERROR = 16;
export declare const EVT_NUMBER_OF_COMPLETED_PACKETS = 19;
export declare const EVT_LE_META_EVENT = 62;
export declare const EVT_LE_CONN_COMPLETE = 1;
export declare const EVT_LE_ADVERTISING_REPORT = 2;
export declare const EVT_LE_CONN_UPDATE_COMPLETE = 3;
export declare const EVT_LE_READ_REMOTE_FEATURES_COMPLETE = 4;
export declare const OGF_LINK_CTL = 1;
export declare const OCF_DISCONNECT = 6;
export declare const OGF_HOST_CTL = 3;
export declare const OCF_SET_EVENT_MASK = 1;
export declare const OCF_RESET = 3;
export declare const OCF_READ_LE_HOST_SUPPORTED = 108;
export declare const OCF_WRITE_LE_HOST_SUPPORTED = 109;
export declare const OGF_INFO_PARAM = 4;
export declare const OCF_READ_LOCAL_VERSION = 1;
export declare const OCF_READ_BUFER_SIZE = 5;
export declare const OCF_READ_BD_ADDR = 9;
export declare const OGF_STATUS_PARAM = 5;
export declare const OCF_READ_RSSI = 5;
export declare const OGF_LE_CTL = 8;
export declare const OCF_LE_SET_EVENT_MASK = 1;
export declare const OCF_LE_READ_BUFFER_SIZE = 2;
export declare const OCF_LE_SET_ADVERTISING_PARAMETERS = 6;
export declare const OCF_LE_SET_ADVERTISING_DATA = 8;
export declare const OCF_LE_SET_SCAN_RESPONSE_DATA = 9;
export declare const OCF_LE_SET_ADVERTISE_ENABLE = 10;
export declare const OCF_LE_SET_SCAN_PARAMETERS = 11;
export declare const OCF_LE_SET_SCAN_ENABLE = 12;
export declare const OCF_LE_CREATE_CONN = 13;
export declare const OCF_LE_CANCEL_CONN = 14;
export declare const OCF_LE_CONN_UPDATE = 19;
export declare const OCF_LE_START_ENCRYPTION = 25;
export declare const OCF_LE_LTK_NEG_REPLY = 27;
export declare const DISCONNECT_CMD: number;
export declare const SET_EVENT_MASK_CMD: number;
export declare const RESET_CMD: number;
export declare const READ_LE_HOST_SUPPORTED_CMD: number;
export declare const WRITE_LE_HOST_SUPPORTED_CMD: number;
export declare const READ_LOCAL_VERSION_CMD: number;
export declare const READ_BUFFER_SIZE_CMD: number;
export declare const READ_BD_ADDR_CMD: number;
export declare const READ_RSSI_CMD: number;
export declare const LE_SET_EVENT_MASK_CMD: number;
export declare const LE_SET_SCAN_PARAMETERS_CMD: number;
export declare const LE_SET_SCAN_ENABLE_CMD: number;
export declare const LE_CREATE_CONN_CMD: number;
export declare const LE_CANCEL_CONN_CMD: number;
export declare const LE_CONN_UPDATE_CMD: number;
export declare const LE_START_ENCRYPTION_CMD: number;
export declare const LE_READ_BUFFER_SIZE_CMD: number;
export declare const LE_SET_ADVERTISING_PARAMETERS_CMD: number;
export declare const LE_SET_ADVERTISING_DATA_CMD: number;
export declare const LE_SET_SCAN_RESPONSE_DATA_CMD: number;
export declare const LE_SET_ADVERTISE_ENABLE_CMD: number;
export declare const LE_LTK_NEG_REPLY_CMD: number;
export declare const HCI_OE_USER_ENDED_CONNECTION = 19;
export declare const ATT_OP_ERROR = 1;
export declare const ATT_OP_MTU_REQ = 2;
export declare const ATT_OP_MTU_RESP = 3;
export declare const ATT_OP_FIND_INFO_REQ = 4;
export declare const ATT_OP_FIND_INFO_RESP = 5;
export declare const ATT_OP_FIND_BY_TYPE_REQ = 6;
export declare const ATT_OP_FIND_BY_TYPE_RESP = 7;
export declare const ATT_OP_READ_BY_TYPE_REQ = 8;
export declare const ATT_OP_READ_BY_TYPE_RESP = 9;
export declare const ATT_OP_READ_REQ = 10;
export declare const ATT_OP_READ_RESP = 11;
export declare const ATT_OP_READ_BLOB_REQ = 12;
export declare const ATT_OP_READ_BLOB_RESP = 13;
export declare const ATT_OP_READ_MULTI_REQ = 14;
export declare const ATT_OP_READ_MULTI_RESP = 15;
export declare const ATT_OP_READ_BY_GROUP_REQ = 16;
export declare const ATT_OP_READ_BY_GROUP_RESP = 17;
export declare const ATT_OP_WRITE_REQ = 18;
export declare const ATT_OP_WRITE_RESP = 19;
export declare const ATT_OP_PREPARE_WRITE_REQ = 22;
export declare const ATT_OP_PREPARE_WRITE_RESP = 23;
export declare const ATT_OP_EXECUTE_WRITE_REQ = 24;
export declare const ATT_OP_EXECUTE_WRITE_RESP = 25;
export declare const ATT_OP_HANDLE_NOTIFY = 27;
export declare const ATT_OP_HANDLE_IND = 29;
export declare const ATT_OP_HANDLE_CNF = 30;
export declare const ATT_OP_WRITE_CMD = 82;
export declare const ATT_OP_SIGNED_WRITE_CMD = 210;
export declare const ATT_ECODE_SUCCESS = 0;
export declare const ATT_ECODE_INVALID_HANDLE = 1;
export declare const ATT_ECODE_READ_NOT_PERM = 2;
export declare const ATT_ECODE_WRITE_NOT_PERM = 3;
export declare const ATT_ECODE_INVALID_PDU = 4;
export declare const ATT_ECODE_AUTHENTICATION = 5;
export declare const ATT_ECODE_REQ_NOT_SUPP = 6;
export declare const ATT_ECODE_INVALID_OFFSET = 7;
export declare const ATT_ECODE_AUTHORIZATION = 8;
export declare const ATT_ECODE_PREP_QUEUE_FULL = 9;
export declare const ATT_ECODE_ATTR_NOT_FOUND = 10;
export declare const ATT_ECODE_ATTR_NOT_LONG = 11;
export declare const ATT_ECODE_INSUFF_ENCR_KEY_SIZE = 12;
export declare const ATT_ECODE_INVAL_ATTR_VALUE_LEN = 13;
export declare const ATT_ECODE_UNLIKELY = 14;
export declare const ATT_ECODE_INSUFF_ENC = 15;
export declare const ATT_ECODE_UNSUPP_GRP_TYPE = 16;
export declare const ATT_ECODE_INSUFF_RESOURCES = 17;
export declare const GATT_PRIM_SVC_UUID = 10240;
export declare const GATT_INCLUDE_UUID = 10242;
export declare const GATT_CHARAC_UUID = 10243;
export declare const GATT_CLIENT_CHARAC_CFG_UUID = 10498;
export declare const GATT_SERVER_CHARAC_CFG_UUID = 10499;
export declare const ATT_CID = 4;
//# sourceMappingURL=HciCodes.d.ts.map